### ISSUE TITLE
El Capitan upgrade upset brewdo resources

### ISSUE THREAD

**Issue by zigg** [brewdo/brewdo#11]
The El Capitan public beta upset a few things.
-   `/usr/local` was changed to `root`:`wheel` ownership.  Restored by changing ownership back to `_homebrew`:`wheel`.
-   `/var/log/homebrew` vanished.  Restored by `sudo brewdo mkdirs`.

Currently running into build errors seemingly unrelated to brewdo.

**Comment by zigg** [comment]
Rolled Xcode up to 7.0 beta 3 and added the matching CLI tools and building appears to be working again.

Looks like we just need a nice way to solve the above problems.

**Comment by alexreg** [comment]
I believe this is solved in my latest (pending) release. Closing for now.
