### ISSUE TITLE
Added _homebrew user to admin group

### ISSUE THREAD

**Issue by alexreg** [brewdo/brewdo#18]
This is needed in order to do `brew linkapps`. See issue https://github.com/Homebrew/brew/issues/1544.

**Comment by zigg** [comment]
This should be relatively easy to add for new setups, but we'll also need to consider existing users. Ideally, that group membership should be automatically added when someone uses an updated brewdo for the first time.

**Comment by alexreg** [comment]
Right.

**Comment by alexreg** [comment]
Closing, since brew removed its `linkapps` command some time ago.
